rvm: 2.2

sudo: required
services: docker

before_install: curl -L https://www.getchef.com/chef/install.sh | sudo bash -s -- -P chefdk -v 0.19.6
install:
  - chef exec bundle
  - chef exec berks

before_script: sudo iptables -L DOCKER || sudo iptables -N DOCKER

script:
  - chef exec rake foodcritic .
  # Run test-kitchen with docker driver, for example:
  - chef exec rake 'integration:docker[ci,test]'
